version: "3.7"

services:
   paperplane:
      build: .
      volumes: 
         - "./userbot.session:/usr/src/app/userbot.session"
         - "./config.env:/usr/src/app/config.env"
      depends_on: 
         - mongoserver
      restart: unless-stopped

   mongoserver:
      image: mongo:latest
      restart: unless-stopped
      ports:
         - "27017:27017"
      volumes:
         - mongodb_data:/data/db
      environment:
         MONGO_INITDB_ROOT_USERNAME: paperplane
         MONGO_INITDB_ROOT_PASSWORD: paperplane
         MONGO_INITDB_DATABASE: userbot

volumes:
   mongodb_data:
      driver: local
